export { createVibeTreeServer } from './server';
export type { CreateServerOptions, VibeTreeServer } from './server';
export { loadConfigFromEnv } from './config';
export type { ServerConfig } from './config';
export { ShellManager } from './services/ShellManager';
export type { PtySpawn, ShellSettings } from './services/ShellManager';
export { AuthService } from './auth/AuthService';
export { setupWebSocketHandlers } from './api/websocket';
export type { SessionHooks } from './api/websocket';
export { setupRestRoutes } from './api/rest';
export { listDirectory, discoverRepos } from './services/fs-browse';
export type { DirectoryListing, DirectoryEntry, DiscoveredRepo } from './services/fs-browse';
export { AgentStateTracker } from './services/AgentStateTracker';
export type { AgentState, AgentStateEntry } from './services/AgentStateTracker';
